### PR TITLE
feat: create publish workflow

### PR DESCRIPTION
**Pull request by danjohnson95**
Work in progress - I'll let you know when this is good for review

### CODE REVIEW

**Comment by LukeTowers** [comment]
Note for future ref: discussion on #16.

@danjohnson95 @ianlandsman what's left on this? I'd love to get the notifier actually running on my macbook 😉

**Comment by danjohnson95** [comment]
I'd also love to get this running on my MacBook, but we can't publish in a CI environment until https://github.com/NativePHP/electron/pull/74#issuecomment-1792973094 is approved and merged 😞

**Comment by LukeTowers** [comment]
@danjohnson95 good news! It's merged now 😄

**Comment by danjohnson95** [comment]
Excellent! I've bumped the composer file to point to the specific commit because it hasn't been tagged yet.

This should be everything required to build in CI for macOS, upload to GitHub Releases, and automatically roll out the update to existing users.

Once this is merged in, I'll keep an eye on the pipeline to see if it works as intended and I may need to raise a separate PR to fix any potential issues.

**Comment by LukeTowers** [comment]
@ianlandsman looks like something you need to fix: https://github.com/UserScape/larajobs-desktop/actions/runs/7352162872/job/20016515689#step:8:167

**Comment by ianlandsman** [comment]
Sorry for the delay, not totally clear what that error is but there was an agreement to agree to in the apple dev console so I did that.

**Comment by LukeTowers** [comment]
@danjohnson95 any idea what's going wrong in the logs here: https://github.com/UserScape/larajobs-desktop/actions/runs/7352162872/job/20671888416#step:8:135?

**Pull request merged**
